apiVersion: v1
kind: ConfigMap
metadata:
  name: postech-app-config
  namespace: ${K8S_NAMESPACE:-postech-fase2}
data:
  DATABASE_URL: "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${K8S_POSTGRES_NAME:-postgres}-service:${DB_PORT:-5432}/${POSTGRES_DB:-tech_challenge}"
  POSTGRES_DB: "${POSTGRES_DB:-tech_challenge}"
  POSTGRES_USER: "${POSTGRES_USER:-postgres}"
  PYTHONPATH: "${PYTHONPATH:-/app}"
  PYTHONUNBUFFERED: "${PYTHONUNBUFFERED:-1}"
  PYTHONDONTWRITEBYTECODE: "${PYTHONDONTWRITEBYTECODE:-1}" 