apiVersion: v1
kind: ConfigMap
metadata:
  name: postech-app-config
  namespace: postech-fase2
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/tech_challenge"
  POSTGRES_DB: "tech_challenge"
  POSTGRES_USER: "postgres"
  PYTHONPATH: "/app"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1" 