apiVersion: v1
kind: Secret
metadata:
  name: postech-app-secret
  namespace: ${K8S_NAMESPACE:-postech-fase2}
type: Opaque
data:
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_B64:-cG9zdGdyZXM=}  # postgres em base64
  SECRET_KEY: ${SECRET_KEY_B64:-eW91cl9zZWNyZXRfa2V5X2hlcmU=}  # your_secret_key_here em base64 