services:
  # API FastAPI
  - type: web
    name: fastfood-api
    env: python
    plan: free
    buildCommand: pip install poetry && poetry install --no-dev
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastfood-db
          property: connectionString
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: MERCADOPAGO_WEBHOOK_URL
        value: https://fastfood-api.onrender.com/webhook
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION
        value: 30
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
    healthCheckPath: /health

  # Banco de dados PostgreSQL
  - type: pserv
    name: fastfood-db
    env: postgresql
    plan: free
    ipAllowList: [] 