"""adicionar_coluna_observacoes_pedidos

Revision ID: 406649bad7e7
Revises: b50c36ddab38
Create Date: 2025-08-05 23:36:37.301045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406649bad7e7'
down_revision: Union[str, None] = 'b50c36ddab38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tb_categorias', ['id'])
    op.create_unique_constraint(None, 'tb_clientes', ['id'])
    op.create_unique_constraint(None, 'tb_fila_pedidos', ['id'])
    op.create_unique_constraint(None, 'tb_pagamentos', ['id'])
    op.add_column('tb_pedidos', sa.Column('observacoes', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'tb_pedidos', ['id'])
    op.create_unique_constraint(None, 'tb_produtos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_produtos', type_='unique')
    op.drop_constraint(None, 'tb_pedidos', type_='unique')
    op.drop_column('tb_pedidos', 'observacoes')
    op.drop_constraint(None, 'tb_pagamentos', type_='unique')
    op.drop_constraint(None, 'tb_fila_pedidos', type_='unique')
    op.drop_constraint(None, 'tb_clientes', type_='unique')
    op.drop_constraint(None, 'tb_categorias', type_='unique')
    # ### end Alembic commands ###
