"""altera tipo da primary key da tabela clientes

Revision ID: 64c459dea633
Revises: bf181f001f8d
Create Date: 2025-05-22 00:02:57.152834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c459dea633'
down_revision: Union[str, None] = 'bf181f001f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clientes', 'id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'clientes', ['id'])
    op.create_unique_constraint(None, 'fila_pedidos', ['id'])
    op.create_unique_constraint(None, 'pedidos', ['id'])
    op.create_unique_constraint(None, 'produtos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='unique')
    op.drop_constraint(None, 'pedidos', type_='unique')
    op.drop_constraint(None, 'fila_pedidos', type_='unique')
    op.drop_constraint(None, 'clientes', type_='unique')
    op.alter_column('clientes', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
