"""criar unique constraints

Revision ID: a500ce3feb64
Revises: ac0c3d079b11
Create Date: 2025-05-29 00:35:16.456938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a500ce3feb64'
down_revision: Union[str, None] = 'ac0c3d079b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categorias', ['id'])
    op.create_unique_constraint(None, 'clientes', ['id'])
    op.create_unique_constraint(None, 'fila_pedidos', ['id'])
    op.create_unique_constraint(None, 'pagamentos', ['id'])
    op.create_unique_constraint(None, 'pedidos', ['id'])
    op.create_unique_constraint(None, 'produtos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='unique')
    op.drop_constraint(None, 'pedidos', type_='unique')
    op.drop_constraint(None, 'pagamentos', type_='unique')
    op.drop_constraint(None, 'fila_pedidos', type_='unique')
    op.drop_constraint(None, 'clientes', type_='unique')
    op.drop_constraint(None, 'categorias', type_='unique')
    # ### end Alembic commands ###
